#!/usr/bin/env bash
# VRPRM RL v2 (exploratory): unlock the optimization + FirstError localization
# reward + entropy-ordered data. The SFT checkpoint stays FROZEN.
#
# This script is SELF-CONTAINED (it no longer wraps train_vrprm_rl.sh) and uses
# the reorganized repository layout:
#
#   SFT checkpoint  ../backup/VRPRM_v2.0_artifacts/sft_output/.../checkpoint-513-merge
#   raw VisualPRM   ../backup/release_v1/huggingface_datasets/VisualPRM400K-v1.1-Raw
#   base RL splits  ../backup/VRPRM_v2.0_artifacts/data/...
#   entropy split   easyr1/data/visualprm400k_..._balanced_40k_entropy
#
# Differences vs. the paper run (train_vrprm_rl.sh), all RL-side:
#
#   optimization   lr 5e-9 -> 1e-7, KL coef 0.2 -> 1e-2, 600 -> 1200 steps,
#                  rollout temperature 0.8 -> 1.0 (top-p 1.0). The paper
#                  setting was intentionally conservative and barely moved
#                  the policy; these values release that headroom.
#   filtering      online_filtering on [0.05, 0.95]: degenerate groups (all
#                  rollouts fully right or fully wrong) are skipped instead
#                  of wasting rollout compute (J1/DAPO/MJ1 practice).
#   reward         reward_source_macro_localize.py: <answer> gains a
#                  "FirstError: j" line (guided-decoding enforced, learnable
#                  without SFT). R_cons = min(macro-F1, localization) couples
#                  the rationale to the judgments; think band widened to
#                  [80, 2400] chars (hard cap stays max_response_length).
#   data           entropy-ordered RL split (uncertainty-first curriculum):
#                  run run_entropy_select.sh once against the merged SFT
#                  checkpoint; it reorders the 40K pool so the samples the
#                  SFT model is least consistent on are trained first.
#                  DATA_SHUFFLE=false preserves the order.
#
# Every knob remains overridable; the values below are the v2 defaults.
#
# 8xH200 preset — run as:
#   N_GPUS_PER_NODE=8 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
#     ROLLOUT_BATCH_SIZE=64 MINI_ROLLOUT_BATCH_SIZE=32 \
#     MICRO_BATCH_SIZE_UPDATE=8 MICRO_BATCH_SIZE_EXPERIENCE=8 \
#     VLLM_MAX_NUM_BATCHED_TOKENS=131072 GPU_MEMORY_UTILIZATION=0.80 \
#     VAL_BATCH_SIZE=128 bash easyr1/examples/vrprm/train_vrprm_rl_v2.sh
# Rationale: TP=1 per GPU gives 8 data-parallel vLLM rollout engines (the 8B
# model fits one H200 easily); FSDP shards the LoRA update across 8 GPUs;
# rollout_batch 32->64 improves generation batching while global_batch_size
# stays 16 prompts x 16 rollouts per optimizer step (update semantics
# unchanged); micro batch 2->8 exploits the 141GB headroom.
set -euo pipefail
set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EASYR1_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VRPRM_ROOT="$(cd "${EASYR1_ROOT}/.." && pwd)"
OPENSOURCE_ROOT="$(cd "${VRPRM_ROOT}/.." && pwd)"
BACKUP_ARTIFACTS="${OPENSOURCE_ROOT}/backup/VRPRM_v2.0_artifacts"

# ---------------------------------------------------------------- paths ----
BASE_MODEL_PATH="${BASE_MODEL_PATH:-/mnt/shared-storage-user/chenxinquan/Qwen3-VL-8B-Thinking}"
DEFAULT_SFT_MODEL="${BACKUP_ARTIFACTS}/sft_output/qwen3_vl_8b_thinking_global_stepwise_multiturn_sft/v0-20260628-015250/checkpoint-513-merge"
MODEL_PATH="${MODEL_PATH:-${DEFAULT_SFT_MODEL}}"

# Raw VisualPRM400K after reorganization. RL rows reference images as
# "VisualPRM400K-v1.1-Raw/images/...", so IMAGE_DIR must be the directory
# that CONTAINS VisualPRM400K-v1.1-Raw (not the dataset dir itself).
RAW_DATA_ROOT="${RAW_DATA_ROOT:-${OPENSOURCE_ROOT}/backup/release_v1/huggingface_datasets/VisualPRM400K-v1.1-Raw}"
IMAGE_DIR="${IMAGE_DIR:-$(cd "${RAW_DATA_ROOT}/.." && pwd)}"

# Base splits produced by the paper pipeline (kept in the artifacts backup);
# they are rebuilt automatically from the raw data if missing.
SOURCE_DATASET_DIR="${SOURCE_DATASET_DIR:-${BACKUP_ARTIFACTS}/data/visualprm400k_filtered_source_cases_clean_pos0875_pool150k_balanced}"
BASE_DATASET_DIR="${BASE_DATASET_DIR:-${BACKUP_ARTIFACTS}/data/visualprm400k_source_macro_rl_clean_pos0875_balanced_40k}"
# Entropy-ordered split generated by run_entropy_select.sh (lives under
# easyr1/data/ because it is a derived, regenerable artifact).
DATASET_DIR="${DATASET_DIR:-${EASYR1_ROOT}/data/visualprm400k_source_macro_rl_clean_pos0875_balanced_40k_entropy}"

if [[ ! -d "${MODEL_PATH}" && "${MODEL_PATH}" != Qwen/* && "${MODEL_PATH}" != */* ]]; then
  echo "Model path not found: ${MODEL_PATH}" >&2
  echo "Set MODEL_PATH to a merged SFT HF directory or a Hub model id." >&2
  exit 1
fi
if [[ ! -d "${RAW_DATA_ROOT}" ]]; then
  echo "VisualPRM400K raw data directory not found: ${RAW_DATA_ROOT}" >&2
  echo "Set RAW_DATA_ROOT to your local VisualPRM400K-v1.1-Raw directory." >&2
  exit 1
fi

cd "${EASYR1_ROOT}"

if [[ -d "${MODEL_PATH}" && -f "${MODEL_PATH}/config.json" && -f "${BASE_MODEL_PATH}/config.json" ]]; then
  python3 scripts/fix_qwen3vl_config_rope.py \
    "${MODEL_PATH}" \
    --reference-config "${BASE_MODEL_PATH}/config.json"
fi

# ----------------------------------------------------------------- data ----
# Auto-prepare the base RL splits with paper defaults (independent of
# train_vrprm_rl.sh). The entropy split is then derived by run_entropy_select.sh.
if [[ ! -f "${SOURCE_DATASET_DIR}/train_source.jsonl" || ! -f "${SOURCE_DATASET_DIR}/test_source.jsonl" || ! -f "${SOURCE_DATASET_DIR}/.visualprm_filtered_source_cases_v1" || "${REBUILD_SOURCE_DATASET:-false}" == "true" ]]; then
  python3 scripts/prepare_visualprm400k_filtered_source_cases.py \
    --data-root "${RAW_DATA_ROOT}" \
    --output-dir "${SOURCE_DATASET_DIR}" \
    --negative-threshold "${NEGATIVE_THRESHOLD:-0.125}" \
    --positive-threshold "${POSITIVE_THRESHOLD:-0.875}" \
    --target-negative-source-ratio "${TARGET_NEGATIVE_SOURCE_RATIO:-0.50}" \
    --target-negative-step-ratio "${TARGET_NEGATIVE_STEP_RATIO:-0.32}" \
    --max-train-source-samples "${MAX_TRAIN_SOURCE_SAMPLES:-150000}" \
    --max-val-source-samples "${MAX_VAL_SOURCE_SAMPLES:-2000}" \
    --max-all-positive-per-batch-ratio "${MAX_ALL_POSITIVE_PER_BATCH_RATIO:-0.50}" \
    --batch-size-for-ordering "${BATCH_SIZE_FOR_ORDERING:-${MINI_ROLLOUT_BATCH_SIZE:-16}}" \
    --val-ratio "${VAL_RATIO:-0.01}" \
    --seed "${DATA_SEED:-42}" \
    --limit "${DATA_LIMIT:-0}"
fi

if [[ ! -f "${BASE_DATASET_DIR}/train.jsonl" || ! -f "${BASE_DATASET_DIR}/test.jsonl" || ! -f "${BASE_DATASET_DIR}/.visualprm_source_macro_paths_v1" || "${REBUILD_DATASET:-false}" == "true" ]]; then
  python3 scripts/prepare_visualprm400k_source_macro_rl.py \
    --source-dir "${SOURCE_DATASET_DIR}" \
    --output-dir "${BASE_DATASET_DIR}" \
    --max-train-samples "${MAX_TRAIN_SAMPLES:-40000}" \
    --max-val-samples "${MAX_VAL_SAMPLES:-2000}" \
    --target-negative-source-ratio "${TARGET_NEGATIVE_SOURCE_RATIO:-0.50}" \
    --target-negative-step-ratio "${TARGET_NEGATIVE_STEP_RATIO:-0.32}" \
    --hard-mixed-bonus "${HARD_MIXED_BONUS:-0.03}" \
    --seed "${DATA_SEED:-42}"
fi

if [[ ! -f "${DATASET_DIR}/.entropy_selected" ]]; then
  echo "Entropy-ordered dataset not found: ${DATASET_DIR}" >&2
  echo "Run: bash ${SCRIPT_DIR}/run_entropy_select.sh   (serves/queries the merged SFT checkpoint)" >&2
  echo "Or set DATASET_DIR=${BASE_DATASET_DIR} to train on the base split without entropy ordering." >&2
  exit 1
fi

# -------------------------------------------------------------- v2 knobs ----
# Optimization headroom (v2).
LEARNING_RATE="${LEARNING_RATE:-1e-7}"
KL_COEF="${KL_COEF:-1.0e-2}"
MAX_STEPS="${MAX_STEPS:-1200}"
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-1.0}"
ROLLOUT_TOP_P="${ROLLOUT_TOP_P:-1.0}"

# Degenerate-group filtering (v2): skip groups where all rollouts are fully
# right or fully wrong — they produce zero group advantage.
ONLINE_FILTERING="${ONLINE_FILTERING:-true}"
FILTER_LOW="${FILTER_LOW:-0.05}"
FILTER_HIGH="${FILTER_HIGH:-0.95}"

# Entropy curriculum (v2): keep the uncertainty-first order fixed.
DATA_SHUFFLE="${DATA_SHUFFLE:-false}"

# FirstError localization reward (v2).
REWARD_FUNCTION="${REWARD_FUNCTION:-./examples/vrprm/reward_source_macro_localize.py:compute_score}"
FORMAT_PROMPT="${FORMAT_PROMPT:-./examples/vrprm/vrprm_source_macro_localize.jinja}"
REWARD_KWARGS_DEFAULT="{\"step_weight\":${STEP_WEIGHT:-0.75},\"cons_weight\":${CONS_WEIGHT:-0.20},\"format_weight\":${FORMAT_WEIGHT:-0.04},\"think_weight\":${THINK_WEIGHT:-0.01},\"count_weight\":${COUNT_WEIGHT:-0.15},\"min_think_chars\":${MIN_THINK_CHARS:-80},\"max_think_chars\":${MAX_THINK_CHARS:-2400}}"
REWARD_KWARGS="${REWARD_KWARGS_JSON:-${REWARD_KWARGS_DEFAULT}}"

# Guided grammar REQUIRES the FirstError line. The default MUST stay in
# single quotes: in double quotes bash collapses \\s to \s, which makes the
# embedded JSON invalid ("Invalid \\escape") and crashes verl at startup.
if [[ -z "${GUIDED_REGEX:-}" ]]; then
  GUIDED_REGEX='<think>[\\s\\S]*</think>\\s*<answer>(\\s*Step\\s*[0-9]+\\s*:\\s*[01]\\s*)+(\\s*FirstError\\s*:\\s*-?[0-9]+\\s*)</answer>'
fi
ROLLOUT_EXTRA_SAMPLING_PARAMS="${ROLLOUT_EXTRA_SAMPLING_PARAMS:-{\"guided_regex\":\"${GUIDED_REGEX}\"}}"

EXPERIMENT_NAME="${EXPERIMENT_NAME:-vrprm_rl_v2_localize_entropy_40k_1200}"

# --------------------------------------------------------------- launch ----
export PYTHONPATH="${EASYR1_ROOT}:${PYTHONPATH:-}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export VLLM_USE_V1="${VLLM_USE_V1:-1}"
export CUDA_DEVICE_ORDER="${CUDA_DEVICE_ORDER:-PCI_BUS_ID}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export NCCL_ASYNC_ERROR_HANDLING="${NCCL_ASYNC_ERROR_HANDLING:-1}"
export NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}"

RAY_TMPDIR="${RAY_TMPDIR:-/tmp/ray_vrprm_rl}"
if (( ${#RAY_TMPDIR} > 50 )); then
  RAY_TMPDIR="/tmp/ray_vrprm_rl"
fi
export RAY_TMPDIR
mkdir -p "${RAY_TMPDIR}"

CACHE_ROOT="${CACHE_ROOT:-${VRPRM_ROOT}/cache/vrprm_rl}"
export HF_HOME="${HF_HOME:-${CACHE_ROOT}/hf}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-${HF_HOME}/datasets}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/transformers}"
export TMPDIR="${TMPDIR:-${CACHE_ROOT}/tmp}"
export FLASHINFER_WORKSPACE_BASE="${FLASHINFER_WORKSPACE_BASE:-${CACHE_ROOT}/flashinfer}"
export FLASHINFER_CUBIN_DIR="${FLASHINFER_WORKSPACE_BASE}/cubins"
mkdir -p "${HF_DATASETS_CACHE}" "${TRANSFORMERS_CACHE}" "${TMPDIR}" "${FLASHINFER_WORKSPACE_BASE}" "${FLASHINFER_CUBIN_DIR}"

export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_DIR="${WANDB_DIR:-${VRPRM_ROOT}/wandb}"

echo "[v2] lr=${LEARNING_RATE} kl=${KL_COEF} steps=${MAX_STEPS} temp=${ROLLOUT_TEMPERATURE} top_p=${ROLLOUT_TOP_P}"
echo "[v2] reward=${REWARD_FUNCTION}"
echo "[v2] dataset=${DATASET_DIR} (entropy-ordered, shuffle=${DATA_SHUFFLE})"
echo "[v2] images=${IMAGE_DIR}"
echo "[v2] experiment=${EXPERIMENT_NAME}"

python3 -m verl.trainer.main \
  config=examples/config.yaml \
  data.train_files="${DATASET_DIR}/train.jsonl" \
  data.val_files="${DATASET_DIR}/test.jsonl" \
  data.prompt_key=prompt \
  data.answer_key=ground_truth \
  data.image_key=images \
  data.shuffle="${DATA_SHUFFLE}" \
  data.image_dir="${IMAGE_DIR}" \
  data.format_prompt="${FORMAT_PROMPT}" \
  data.max_prompt_length="${MAX_PROMPT_LENGTH:-8192}" \
  data.max_response_length="${MAX_RESPONSE_LENGTH:-2048}" \
  data.rollout_batch_size="${ROLLOUT_BATCH_SIZE:-32}" \
  data.mini_rollout_batch_size="${MINI_ROLLOUT_BATCH_SIZE:-16}" \
  data.val_batch_size="${VAL_BATCH_SIZE:-64}" \
  data.min_pixels="${MIN_PIXELS:-200704}" \
  data.max_pixels="${MAX_PIXELS:-1048576}" \
  data.filter_overlong_prompts="${FILTER_OVERLONG_PROMPTS:-true}" \
  data.filter_overlong_prompts_workers="${FILTER_OVERLONG_PROMPTS_WORKERS:-8}" \
  worker.actor.model.model_path="${MODEL_PATH}" \
  worker.actor.model.trust_remote_code="${TRUST_REMOTE_CODE:-true}" \
  worker.actor.model.freeze_vision_tower="${FREEZE_VISION_TOWER:-true}" \
  worker.actor.model.lora.rank="${LORA_RANK:-16}" \
  worker.actor.model.lora.alpha="${LORA_ALPHA:-32}" \
  worker.actor.model.lora.target_modules="${LORA_TARGET_MODULES:-all-linear}" \
  worker.actor.model.lora.exclude_modules="${LORA_EXCLUDE_MODULES:-.*visual.*}" \
  worker.actor.fsdp.torch_dtype="${TORCH_DTYPE:-bf16}" \
  worker.actor.optim.strategy="${OPTIM_STRATEGY:-adamw_bf16}" \
  worker.actor.optim.lr="${LEARNING_RATE}" \
  worker.actor.optim.weight_decay="${WEIGHT_DECAY:-1e-2}" \
  worker.actor.global_batch_size="${GLOBAL_BATCH_SIZE:-16}" \
  worker.actor.micro_batch_size_per_device_for_update="${MICRO_BATCH_SIZE_UPDATE:-2}" \
  worker.actor.micro_batch_size_per_device_for_experience="${MICRO_BATCH_SIZE_EXPERIENCE:-2}" \
  worker.actor.loss_type="${ACTOR_LOSS_TYPE:-gspo_token}" \
  worker.actor.loss_avg_mode="${LOSS_AVG_MODE:-seq}" \
  worker.actor.clip_ratio_low="${CLIP_RATIO_LOW:-3e-4}" \
  worker.actor.clip_ratio_high="${CLIP_RATIO_HIGH:-4e-4}" \
  worker.actor.offload.offload_params="${ACTOR_OFFLOAD_PARAMS:-false}" \
  worker.actor.offload.offload_optimizer="${ACTOR_OFFLOAD_OPTIMIZER:-false}" \
  worker.ref.fsdp.enable_cpu_offload="${REF_CPU_OFFLOAD:-false}" \
  worker.rollout.n="${ROLLOUT_N:-16}" \
  worker.rollout.temperature="${ROLLOUT_TEMPERATURE}" \
  worker.rollout.top_p="${ROLLOUT_TOP_P}" \
  worker.rollout.tensor_parallel_size="${TENSOR_PARALLEL_SIZE:-1}" \
  worker.rollout.gpu_memory_utilization="${GPU_MEMORY_UTILIZATION:-0.75}" \
  worker.rollout.max_num_batched_tokens="${VLLM_MAX_NUM_BATCHED_TOKENS:-49152}" \
  worker.rollout.limit_images="${ROLLOUT_LIMIT_IMAGES:-0}" \
  worker.rollout.enable_chunked_prefill="${ENABLE_CHUNKED_PREFILL:-true}" \
  worker.rollout.extra_sampling_params="${ROLLOUT_EXTRA_SAMPLING_PARAMS}" \
  worker.reward.reward_function="${REWARD_FUNCTION}" \
  worker.reward.reward_function_kwargs="${REWARD_KWARGS}" \
  algorithm.adv_estimator=grpo \
  algorithm.disable_kl="${DISABLE_KL:-false}" \
  algorithm.use_kl_loss="${USE_KL_LOSS:-true}" \
  algorithm.kl_penalty="${KL_PENALTY:-low_var_kl}" \
  algorithm.kl_coef="${KL_COEF}" \
  algorithm.online_filtering="${ONLINE_FILTERING}" \
  algorithm.filter_key="${FILTER_KEY:-overall}" \
  algorithm.filter_low="${FILTER_LOW}" \
  algorithm.filter_high="${FILTER_HIGH}" \
  trainer.total_epochs="${TOTAL_EPOCHS:-1}" \
  trainer.max_steps="${MAX_STEPS}" \
  trainer.project_name="${PROJECT_NAME:-visualprm_easy_r1}" \
  trainer.experiment_name="${EXPERIMENT_NAME}" \
  trainer.logger="${LOGGER:-[\"file\",\"wandb\"]}" \
  trainer.nnodes="${NNODES:-1}" \
  trainer.n_gpus_per_node="${N_GPUS_PER_NODE:-2}" \
  trainer.val_freq="${VAL_FREQ:-50}" \
  trainer.val_before_train="${VAL_BEFORE_TRAIN:-true}" \
  trainer.val_generations_to_log="${VAL_GENERATIONS_TO_LOG:-16}" \
  trainer.train_rollouts_to_log="${TRAIN_ROLLOUTS_TO_LOG:-16}" \
  trainer.train_rollout_log_freq="${TRAIN_ROLLOUT_LOG_FREQ:-10}" \
  trainer.generation_log_max_chars="${GENERATION_LOG_MAX_CHARS:-6000}" \
  trainer.save_freq="${SAVE_FREQ:-50}" \
  trainer.save_limit="${SAVE_LIMIT:-5}" \
  trainer.save_model_only="${SAVE_MODEL_ONLY:-false}" \
  trainer.save_checkpoint_path="${SAVE_CHECKPOINT_PATH:-${EASYR1_ROOT}/checkpoints/visualprm_easy_r1/${EXPERIMENT_NAME}}"
