#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EASYR1_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VRPRM_ROOT="$(cd "${EASYR1_ROOT}/.." && pwd)"

export SOURCE_DATASET_DIR="${SOURCE_DATASET_DIR:-${EASYR1_ROOT}/data/visualprm400k_filtered_source_cases_clean_pos0875_pool150k_balanced}"
export DATASET_DIR="${DATASET_DIR:-${EASYR1_ROOT}/data/visualprm400k_source_macro_rl_clean_pos0875_balanced_40k}"

export NEGATIVE_THRESHOLD="${NEGATIVE_THRESHOLD:-0.125}"
export POSITIVE_THRESHOLD="${POSITIVE_THRESHOLD:-0.875}"
export TARGET_NEGATIVE_SOURCE_RATIO="${TARGET_NEGATIVE_SOURCE_RATIO:-0.50}"
export TARGET_NEGATIVE_STEP_RATIO="${TARGET_NEGATIVE_STEP_RATIO:-0.32}"
export HARD_MIXED_BONUS="${HARD_MIXED_BONUS:-0.03}"
export MAX_TRAIN_SOURCE_SAMPLES="${MAX_TRAIN_SOURCE_SAMPLES:-150000}"
export MAX_VAL_SOURCE_SAMPLES="${MAX_VAL_SOURCE_SAMPLES:-2000}"
export MAX_TRAIN_SAMPLES="${MAX_TRAIN_SAMPLES:-40000}"
export MAX_VAL_SAMPLES="${MAX_VAL_SAMPLES:-2000}"
export DATA_SHUFFLE="${DATA_SHUFFLE:-true}"
export DATA_SEED="${DATA_SEED:-42}"

export MAX_STEPS="${MAX_STEPS:-600}"
export SAVE_FREQ="${SAVE_FREQ:-50}"
export VAL_FREQ="${VAL_FREQ:-50}"
export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-true}"
export VAL_GENERATIONS_TO_LOG="${VAL_GENERATIONS_TO_LOG:-16}"
export TRAIN_ROLLOUTS_TO_LOG="${TRAIN_ROLLOUTS_TO_LOG:-16}"
export TRAIN_ROLLOUT_LOG_FREQ="${TRAIN_ROLLOUT_LOG_FREQ:-10}"
export GENERATION_LOG_MAX_CHARS="${GENERATION_LOG_MAX_CHARS:-6000}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-1}"

export LEARNING_RATE="${LEARNING_RATE:-5e-9}"
export KL_COEF="${KL_COEF:-2.0e-1}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-2048}"
export STEP_WEIGHT="${STEP_WEIGHT:-0.97}"
export FORMAT_WEIGHT="${FORMAT_WEIGHT:-0.02}"
export THINK_WEIGHT="${THINK_WEIGHT:-0.01}"
export COUNT_WEIGHT="${COUNT_WEIGHT:-0.15}"
export MIN_THINK_CHARS="${MIN_THINK_CHARS:-80}"
export MAX_THINK_CHARS="${MAX_THINK_CHARS:-1200}"

export ROLLOUT_N="${ROLLOUT_N:-16}"
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-32}"
export MINI_ROLLOUT_BATCH_SIZE="${MINI_ROLLOUT_BATCH_SIZE:-16}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-16}"
export MICRO_BATCH_SIZE_UPDATE="${MICRO_BATCH_SIZE_UPDATE:-2}"
export MICRO_BATCH_SIZE_EXPERIENCE="${MICRO_BATCH_SIZE_EXPERIENCE:-2}"
export VLLM_MAX_NUM_BATCHED_TOKENS="${VLLM_MAX_NUM_BATCHED_TOKENS:-49152}"

export EXPERIMENT_NAME="${EXPERIMENT_NAME:-qwen3_vl_8b_source_macro_visualprm400k_gspo_lora_clean_balanced_40k_600_reward_modify_0723}"
export SAVE_CHECKPOINT_PATH="${SAVE_CHECKPOINT_PATH:-${EASYR1_ROOT}/checkpoints/visualprm_easy_r1/${EXPERIMENT_NAME}}"

exec bash "${SCRIPT_DIR}/qwen3_vl_8b_source_macro_visualprm400k_gspo_lora_clean_hard.sh"
